// ============================================================
// TrailSafe — CSV demo data + real OSM hikes (Overpass + Nominatim)
// Map: OpenTopoMap. Respect OSM/Nominatim usage policies (no heavy scraping).
// ============================================================

const NOMINATIM = 'https://nominatim.openstreetmap.org/search';
const OVERPASS = 'https://overpass-api.de/api/interpreter';
const HTTP_UA = { 'User-Agent': 'TrailSafe/1.0 (educational demo; local use)' };

let searchCenter = { lat: 47.3769, lng: 8.5417, label: 'Zürich (default)' };
let TRAILS = [];
let WAYPOINTS = {};
let map, markerGroup, pathGroup;
let selectedId = null;
let activeFilter = 'all';
let searchQ = '';
let dataSource = 'csv';
let MOUNTAINS = [];
let mountainGroup;
let mountainFilterQ = '';
let selectedMountainId = null;

const MANDATORY_LIMIT_FOOTER_TEXT =
  'For informational use only. Always verify with official sources. Not a substitute for professional judgment.';

/** Shown on every view where a risk score appears — 11pt in CSS, always visible, not behind tap/scroll. */
const AI_SAFETY_DISCLAIMER =
  '⚠ AI-generated estimate — not a safety guarantee. This score is produced by an automated system using environmental data. Conditions can change rapidly and data may be incomplete. Do not use this score as your sole basis for any outdoor decision. Always consult official forecasts and apply your own judgment.';
const WEATHER_ATTRIBUTION_TEXT = 'Weather data provided by OpenWeatherMap';

/** Article 50 EU AI Act — explainer (plain language) for “Learn what this means”. */
const AI_ART50_EXPLAINER =
  'This score was calculated automatically by a machine learning model. No human expert reviewed this specific output. The model uses weather data, terrain information, and historical accident records to estimate environmental risk. It is not infallible.';

/** Markup shown next to every primary risk value (not in settings / help). */
function aiArt50LabelHtml(variant) {
  if (variant === 'compact') {
    return (
      '<span class="ai-tlabel ai-tlabel--ph" role="status"><span class="ai-tlabel-inner" aria-label="AI-generated">🤖 Generated by AI — ' +
      '<button type="button" class="ai-art50-link" aria-label="Learn what this means for this value">Learn what this means</button></span></span>'
    );
  }
  return (
    '<div class="ai-tlabel" role="status">' +
    '<span class="ai-tlabel-inner" aria-label="AI-generated">🤖 Generated by AI — ' +
    '<button type="button" class="ai-art50-link" aria-label="Learn what AI-generated means">Learn what this means</button></span>' +
    '</div>'
  );
}

function openAiArt50ExplainerModal() {
  if (document.getElementById('art50-explain-modal')) return;
  const w = document.createElement('div');
  w.id = 'art50-explain-modal';
  w.className = 'art50-explain';
  w.setAttribute('role', 'dialog');
  w.setAttribute('aria-modal', 'true');
  w.setAttribute('aria-labelledby', 'art50-explain-h');
  w.innerHTML = `
    <div class="art50-explain__bd" aria-hidden="true"></div>
    <div class="art50-explain__pnl">
      <button type="button" class="art50-explain__x" id="art50-explain-x" aria-label="Close">✕</button>
      <h2 id="art50-explain-h" class="art50-explain__h">What this means</h2>
      <p class="art50-explain__txt">${escapeHtml(AI_ART50_EXPLAINER)}</p>
      <button type="button" class="art50-explain__ok" id="art50-explain-ok">Close</button>
    </div>`;
  document.body.appendChild(w);
  const close = function () {
    if (w.parentNode) w.parentNode.removeChild(w);
    document.removeEventListener('keydown', onK, true);
  };
  function onK(e) {
    if (e.key === 'Escape') {
      e.preventDefault();
      close();
    }
  }
  document.addEventListener('keydown', onK, true);
  w.querySelector('.art50-explain__bd').addEventListener('click', close);
  w.querySelector('#art50-explain-x').addEventListener('click', close);
  w.querySelector('#art50-explain-ok').addEventListener('click', close);
  try {
    w.querySelector('#art50-explain-ok').focus();
  } catch (e) { /* */ }
}

function initAiArt50Ui() {
  if (window.__trailsafeArt50Init) return;
  window.__trailsafeArt50Init = true;
  document.addEventListener(
    'click',
    function (e) {
      if (!e.target || !e.target.closest) return;
      if (!e.target.closest('.ai-art50-link')) return;
      e.preventDefault();
      e.stopPropagation();
      e.stopImmediatePropagation();
      openAiArt50ExplainerModal();
    },
    true
  );
}

/** Sum of per-trail incident counts in dataset within radius (geographic data-density proxy). */
const MIN_REGION_INCIDENT_RECORDS = 15;
const INC_COVERAGE_RADIUS_KM = 40;

function incidentRecordSumWithinRadius(t) {
  if (!t || !TRAILS.length) return 0;
  const R = INC_COVERAGE_RADIUS_KM;
  let s = 0;
  for (const o of TRAILS) {
    if (kmAway(t.lat, t.lng, o.lat, o.lng) <= R) s += Math.max(0, parseInt(o.inc, 10) || 0);
  }
  return s;
}

function isLimitedDataZone(t) {
  if (!t) return true;
  return incidentRecordSumWithinRadius(t) < MIN_REGION_INCIDENT_RECORDS;
}

function limitedDataZoneMessageHtml() {
  const n = MIN_REGION_INCIDENT_RECORDS;
  return (
    '<div class="lim-zone" role="status">' +
    '<p class="lim-zone-h">⚠ Limited data zone</p>' +
    '<p class="lim-zone-p">Fewer than ' +
    n +
    ' historical incidents are recorded for this area. Our AI estimate is less reliable here than in better-documented regions. This does not mean the area is safe — it means we have less information.</p>' +
    '<p class="lim-zone-p"><strong>Strongly recommended:</strong> check local guides, trail associations, or cantonal emergency services before proceeding.</p>' +
    '</div>'
  );
}

/**
 * When true, do not show region incident counts as if they were strong statistics.
 * OSM-derived paths: no trail-specific history in our dataset. CSV: 0 incidents = sparse.
 */
function isSparseRiskData(t) {
  if (t && t.source === 'osm') return true;
  const inc = t && t.inc != null ? parseInt(t.inc, 10) : 0;
  if (Number.isNaN(inc) || inc < 1) return true;
  return false;
}

/** Secondary line under every risk score: data / history confidence (not a go/no-go). */
function riskConfidenceLine(t) {
  const m = t.updatedMin != null ? Math.max(0, parseInt(t.updatedMin, 10) || 0) : 0;
  const src = t && t.source === 'osm' ? 'OpenStreetMap path data + live weather feed' : 'CSV history + live weather feed';
  if (isSparseRiskData(t)) {
    return `Uncertainty: High | Confidence: Low | Data source: ${src} | Weather timestamp: ${m} min ago.`;
  }
  const n = t.inc != null ? parseInt(t.inc, 10) || 0 : 0;
  return `Uncertainty: Medium | Confidence: Moderate | Data source: ${src} | Weather timestamp: ${m} min ago | Incident records: ${n}.`;
}

/** Human-readable tier lines — avoid “safe / danger” verdict phrasing. */
function statusTierUserLine(tierKey) {
  switch (String(tierKey).toLowerCase()) {
    case 'safe':
      return 'Estimated conditions: Low';
    case 'caution':
      return 'Estimated conditions: Moderate';
    case 'risk':
      return 'Estimated conditions: Elevated';
    case 'danger':
      return 'Elevated risk indicators detected — see details';
    default:
      return 'Estimated conditions: Moderate';
  }
}

function riskToStatusKey(r) {
  if (r <= 3) return 'safe';
  if (r <= 5.5) return 'caution';
  if (r <= 7.5) return 'risk';
  return 'danger';
}

const OFFICIAL_OK_KEY = 'trailsafe_official_ok';

function hasOfficialSourcesAck() {
  try {
    return sessionStorage.getItem(OFFICIAL_OK_KEY) === '1';
  } catch (e) {
    return window.__trailsafeOfficialOk === true;
  }
}

function setOfficialSourcesAck() {
  try {
    sessionStorage.setItem(OFFICIAL_OK_KEY, '1');
  } catch (e) {
    window.__trailsafeOfficialOk = true;
  }
}

/** Lower (safe) and Moderate (caution) risk bands: require one-time official-sources screen per session. */
function needsLowerModerateSourceGate(t) {
  const sk = t.statusKey || riskToStatusKey(displayRisk(t));
  return sk === 'safe' || sk === 'caution';
}

function showOfficialSourcesModal(onComplete) {
  const wrap = document.createElement('div');
  wrap.className = 'os-gate';
  wrap.setAttribute('role', 'alertdialog');
  wrap.setAttribute('aria-modal', 'true');
  wrap.setAttribute('aria-labelledby', 'os-gate-title');
  wrap.innerHTML = `
    <div class="os-gate__backdrop" aria-hidden="true"></div>
    <div class="os-gate__panel" role="document">
      <h2 id="os-gate-title" class="os-gate__title">Planning outdoors? Check official sources first.</h2>
      <p class="os-gate__intro">These are <strong>risk estimates based on available environmental data</strong>, not a professional or real-time assessment. Also check:</p>
      <ul class="os-gate__list">
        <li>MeteoSwiss mountain forecast: <a href="https://www.meteoswiss.admin.ch/" target="_blank" rel="noopener noreferrer">meteoswiss.admin.ch</a></li>
        <li>SLF Avalanche Bulletin (winter): <a href="https://www.slf.ch/" target="_blank" rel="noopener noreferrer">slf.ch</a></li>
        <li>Local trail or rescue service conditions</li>
      </ul>
      <button type="button" class="os-gate__btn" id="os-gate-btn" disabled>I have checked official sources — show my score</button>
    </div>`;
  document.body.appendChild(wrap);

  const btn = wrap.querySelector('#os-gate-btn');
  const block = function (e) {
    if (e.key === 'Escape') e.stopPropagation();
  };
  document.addEventListener('keydown', block, true);
  wrap.querySelector('.os-gate__backdrop').addEventListener('click', function (e) {
    e.stopPropagation();
  });

  const timer = setTimeout(function () {
    if (btn) {
      btn.disabled = false;
      try {
        btn.focus();
      } catch (e) { /* */ }
    }
  }, 3000);

  btn.addEventListener('click', function () {
    if (btn.disabled) return;
    clearTimeout(timer);
    document.removeEventListener('keydown', block, true);
    setOfficialSourcesAck();
    if (wrap.parentNode) wrap.parentNode.removeChild(wrap);
    if (onComplete) onComplete();
  });
}

/** Heuristic: Switzerland-typical app usage vs abroad (for a short extra notice only). */
function likelySwitzerlandContext() {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
    if (tz === 'Europe/Zurich') return true;
  } catch (e) { /* */ }
  const l = (navigator.language || '').toLowerCase();
  if (l === 'de-ch' || l === 'fr-ch' || l === 'it-ch' || l === 'rm-ch') return true;
  return l.endsWith('-ch');
}

/**
 * Curated, hardcoded official references. ML scores are secondary to these.
 * Region hint only when the browser is unlikely to be CH-focused.
 */
function openOfficialChecklistModal() {
  if (document.getElementById('os-checklist-root')) return;
  const outsideCh = !likelySwitzerlandContext();
  const wrap = document.createElement('div');
  wrap.id = 'os-checklist-root';
  wrap.className = 'os-checklist';
  wrap.setAttribute('role', 'dialog');
  wrap.setAttribute('aria-modal', 'true');
  wrap.setAttribute('aria-labelledby', 'os-checklist-title');
  wrap.innerHTML = `
    <div class="os-checklist__backdrop" aria-hidden="true"></div>
    <div class="os-checklist__panel">
      <button type="button" class="os-checklist__x" id="os-checklist-x" aria-label="Close">✕</button>
      <h2 id="os-checklist-title" class="os-checklist__title">One more tool to inform your planning</h2>
      <p class="os-checklist__intro">In-app risk numbers are <strong>estimates</strong> — the references below are for your decisions, not a substitute for them.</p>
      ${
        outsideCh
          ? '<p class="os-checklist__region" role="note">Your device may be outside Switzerland—if so, also verify local services; the list below is CH-focused.</p>'
          : ''
      }
      <ul class="os-checklist__list" role="list">
        <li>Weather: MeteoSwiss — <a href="https://www.meteoswiss.admin.ch/" target="_blank" rel="noopener noreferrer">meteoswiss.admin.ch</a></li>
        <li>Avalanche risk (CH): SLF White Risk — <a href="https://www.slf.ch/en/avalanche-bulletin/" target="_blank" rel="noopener noreferrer">slf.ch/en/avalanche-bulletin</a></li>
        <li>Emergency (Switzerland): 144 (ambulance) / 1414 (Alpine rescue REGA)</li>
        <li>Trail conditions: Your local hiking club or cantonal authorities</li>
      </ul>
    </div>`;
  document.body.appendChild(wrap);

  function close() {
    if (wrap.parentNode) wrap.parentNode.removeChild(wrap);
    document.removeEventListener('keydown', onKey, true);
  }
  function onKey(e) {
    if (e.key === 'Escape') {
      e.preventDefault();
      close();
    }
  }
  document.addEventListener('keydown', onKey, true);
  wrap.querySelector('.os-checklist__backdrop').addEventListener('click', close);
  const xb = wrap.querySelector('#os-checklist-x');
  if (xb) xb.addEventListener('click', close);
  try {
    xb.focus();
  } catch (e) { /* */ }
}

function initOfficialSourcesUi() {
  if (window.__trailsafeOfficialUiInit) return;
  window.__trailsafeOfficialUiInit = true;
  const listBtn = document.getElementById('btn-official-sources-list');
  if (listBtn) listBtn.addEventListener('click', () => openOfficialChecklistModal());
  const detail = document.getElementById('detail');
  if (detail) {
    detail.addEventListener('click', (ev) => {
      if (ev.target && ev.target.classList && ev.target.classList.contains('btn-official-sources')) {
        openOfficialChecklistModal();
      }
    });
  }
}

const AI_FEATURE_ACK_KEY = 'trailsafe_ai_feature_ack_v1';
const USER_EXPERIENCE_LEVEL_KEY = 'trailsafe_user_experience_level_v1';
const RISK_HISTORY_OPT_IN_KEY = 'trailsafe_risk_history_opt_in_v1';

function getStoredExperienceLevel() {
  try {
    return localStorage.getItem(USER_EXPERIENCE_LEVEL_KEY) || '';
  } catch (e) {
    return '';
  }
}

function setStoredExperienceLevel(level) {
  if (!level) return;
  try {
    localStorage.setItem(USER_EXPERIENCE_LEVEL_KEY, level);
  } catch (e) { /* */ }
}

function clearAllLocalUserData() {
  try {
    const keys = Object.keys(localStorage || {});
    keys.forEach((k) => {
      if (
        k.startsWith('gear_') ||
        k === AI_FEATURE_ACK_KEY ||
        k === USER_EXPERIENCE_LEVEL_KEY ||
        k === RISK_HISTORY_OPT_IN_KEY ||
        k === 'trailsafe_compliance_events'
      ) {
        localStorage.removeItem(k);
      }
    });
  } catch (e) { /* */ }
  try {
    sessionStorage.removeItem(OFFICIAL_OK_KEY);
  } catch (e) { /* */ }
}

function openPrivacySettingsModal() {
  if (document.getElementById('privacy-settings-root')) return;
  const wrap = document.createElement('div');
  wrap.id = 'privacy-settings-root';
  wrap.className = 'privacy-modal';
  wrap.setAttribute('role', 'dialog');
  wrap.setAttribute('aria-modal', 'true');
  wrap.setAttribute('aria-labelledby', 'privacy-title');
  wrap.innerHTML = `
    <div class="privacy-modal__backdrop" aria-hidden="true"></div>
    <div class="privacy-modal__panel">
      <button type="button" class="privacy-modal__x" id="privacy-x" aria-label="Close">✕</button>
      <h2 id="privacy-title" class="privacy-modal__title">Settings -> Privacy</h2>
      <p class="privacy-modal__intro">What we keep and for how long:</p>
      <ul class="privacy-modal__list">
        <li>Your location coordinates: not stored - deleted after each session</li>
        <li>Your experience level and activity preferences: stored until you delete your account</li>
        <li>Your risk score history (if you opt in): stored for 12 months, then automatically deleted</li>
        <li>App usage logs: anonymized after 30 days, deleted after 12 months</li>
      </ul>
      <p class="privacy-modal__foot">To delete all your data: Settings -> Privacy -> Delete my data/or to request to delete all data</p>
      <div class="privacy-modal__actions">
        <button type="button" class="privacy-modal__danger" id="privacy-delete-all">Delete my data</button>
      </div>
    </div>`;
  document.body.appendChild(wrap);

  function close() {
    if (wrap.parentNode) wrap.parentNode.removeChild(wrap);
    document.removeEventListener('keydown', onKey, true);
  }
  function onKey(e) {
    if (e.key === 'Escape') {
      e.preventDefault();
      close();
    }
  }
  document.addEventListener('keydown', onKey, true);
  wrap.querySelector('.privacy-modal__backdrop').addEventListener('click', close);
  wrap.querySelector('#privacy-x').addEventListener('click', close);
  wrap.querySelector('#privacy-delete-all').addEventListener('click', function () {
    const ok = window.confirm(
      'This will permanently delete your account and all associated data. This cannot be undone. Continue?'
    );
    if (!ok) return;
    fetch('/api/privacy/delete-my-data', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ confirm: true }),
    })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('delete_failed'))))
      .then(function () {
        clearAllLocalUserData();
        location.replace('/auth.html');
      })
      .catch(function () {
        alert('Account deletion failed. Please try again.');
      });
  });
}

function initPrivacySettingsUi() {
  if (window.__trailsafePrivacyUiInit) return;
  window.__trailsafePrivacyUiInit = true;
  const settingsBtn = document.getElementById('btn-settings');
  if (settingsBtn) settingsBtn.addEventListener('click', openPrivacySettingsModal);
}

function ensureMandatoryLimitFooter() {
  const ensure = () => {
    let el = document.getElementById('mandatory-limit-footer');
    if (!el) {
      el = document.createElement('div');
      el.id = 'mandatory-limit-footer';
      el.className = 'mandatory-limit-footer';
      el.setAttribute('role', 'note');
      el.textContent = MANDATORY_LIMIT_FOOTER_TEXT;
      document.body.appendChild(el);
    } else if (!el.textContent || el.textContent.trim() !== MANDATORY_LIMIT_FOOTER_TEXT) {
      el.textContent = MANDATORY_LIMIT_FOOTER_TEXT;
    }
  };
  ensure();
  if (window.__trailsafeMandatoryFooterObserver) return;
  const obs = new MutationObserver(() => ensure());
  obs.observe(document.body, { childList: true, subtree: true });
  window.__trailsafeMandatoryFooterObserver = obs;
}

function showMandatoryOnboardingModal(onComplete) {
  if (document.getElementById('onboarding-flow-root')) return;
  const wrap = document.createElement('div');
  wrap.id = 'onboarding-flow-root';
  wrap.className = 'onb';
  wrap.setAttribute('role', 'alertdialog');
  wrap.setAttribute('aria-modal', 'true');
  wrap.setAttribute('aria-labelledby', 'onb-title');
  const screens = [
    {
      title: 'What this app does',
      body:
        'TrailSafe gives you an AI-generated overview of environmental conditions for outdoor activities based on weather data, terrain information, and historical incident records.* It is a planning aid — one input among many.',
      cta: 'Continue',
    },
    {
      title: 'What this app does not do',
      list: [
        'It does not assess your personal fitness or experience*',
        'It does not replace official weather forecasts or avalanche bulletins*',
        'It does not guarantee your safety*',
        'It is not monitored by safety professionals* You are always responsible for your own decisions outdoors.',
      ],
      cta: 'Continue',
    },
    {
      title: 'Before every outing, also check:',
      list: [
        'MeteoSwiss: meteoswiss.admin.ch*',
        'SLF Avalanche Bulletin: slf.ch*',
        'Local emergency number: 112 (EU) / 1414 (Swiss Alpine Rescue)*',
      ],
      cta: "I understand — let's get started",
    },
  ];
  let step = 0;

  function render() {
    const s = screens[step];
    wrap.innerHTML = `
      <div class="onb__backdrop" aria-hidden="true"></div>
      <div class="onb__panel">
        <div class="onb__progress">Step ${step + 1} / ${screens.length}</div>
        <h2 id="onb-title" class="onb__title">${escapeHtml(s.title)}</h2>
        ${
          s.body
            ? `<p class="onb__body">${escapeHtml(s.body)}</p>`
            : `<ul class="onb__list">${(s.list || []).map((x) => `<li>${escapeHtml(x)}</li>`).join('')}</ul>`
        }
        <div class="onb__actions">
          ${step > 0 ? '<button type="button" class="onb__btn onb__btn--back" id="onb-back">Back</button>' : ''}
          <button type="button" class="onb__btn onb__btn--next" id="onb-next">${escapeHtml(s.cta)}</button>
        </div>
      </div>`;

    const back = wrap.querySelector('#onb-back');
    const next = wrap.querySelector('#onb-next');
    if (back) {
      back.addEventListener('click', function () {
        if (step > 0) {
          step -= 1;
          render();
        }
      });
    }
    next.addEventListener('click', function () {
      if (step < screens.length - 1) {
        step += 1;
        render();
        return;
      }
      const now = new Date().toISOString();
      fetch('/api/compliance/onboarding-complete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ completed: true, client_at: now }),
      })
        .then((r) => (r.ok ? r.json() : Promise.reject(new Error('onboarding'))))
        .then((j) => {
          appendClientComplianceLog({
            type: 'mandatory_onboarding_completed_server',
            server_utc: j && j.server_utc,
            clientAt: now,
          });
        })
        .catch(function () {
          appendClientComplianceLog({
            type: 'mandatory_onboarding_completed_server_error',
            clientAt: now,
          });
        })
        .finally(function () {
          if (wrap.parentNode) wrap.parentNode.removeChild(wrap);
          document.removeEventListener('keydown', blockEsc, true);
          if (onComplete) onComplete();
        });
    });
  }

  function blockEsc(e) {
    if (e.key === 'Escape') e.preventDefault();
    e.stopPropagation();
  }
  document.addEventListener('keydown', blockEsc, true);
  document.body.appendChild(wrap);
  render();
}

async function hasCompletedMandatoryOnboarding() {
  try {
    const r = await fetch('/api/auth/me', { credentials: 'include' });
    if (!r.ok) return false;
    const me = await r.json();
    return !!(me && me.onboarding_completed);
  } catch (e) {
    return false;
  }
}

function hasAiFeatureAck() {
  try {
    return !!localStorage.getItem(AI_FEATURE_ACK_KEY);
  } catch (e) {
    return false;
  }
}

function setAiFeatureAckRecord(iso) {
  try {
    const payload = { acceptedAt: iso, v: 1 };
    localStorage.setItem(AI_FEATURE_ACK_KEY, JSON.stringify(payload));
  } catch (e) { /* */ }
  appendClientComplianceLog({ type: 'ai_risk_feature_ack', clientAt: iso });
}

function appendClientComplianceLog(obj) {
  try {
    const k = 'trailsafe_compliance_events';
    const prev = JSON.parse(localStorage.getItem(k) || '[]');
    const next = [...prev, { ...obj, storedAt: new Date().toISOString() }].slice(-40);
    localStorage.setItem(k, JSON.stringify(next));
  } catch (e) { /* */ }
  if (typeof console !== 'undefined' && console.info) {
    console.info('[TrailSafe compliance]', obj);
  }
}

/**
 * Shown the first time the user reaches the main map / risk data (not at registration).
 * Requires all checkboxes; cannot dismiss with backdrop or Escape.
 */
function showAiFeatureDisclaimerModal(onComplete) {
  if (document.getElementById('ai-feature-ack-modal')) return;
  const wrap = document.createElement('div');
  wrap.id = 'ai-feature-ack-modal';
  wrap.className = 'ai-ff';
  wrap.setAttribute('role', 'alertdialog');
  wrap.setAttribute('aria-modal', 'true');
  wrap.setAttribute('aria-labelledby', 'ai-ff-title');
  wrap.innerHTML = `
    <div class="ai-ff__backdrop" aria-hidden="true"></div>
    <div class="ai-ff__panel">
      <h2 id="ai-ff-title" class="ai-ff__title">About this AI feature</h2>
      <p class="ai-ff__p">The risk scores in this app are generated by artificial intelligence. AI systems can make mistakes, produce inaccurate outputs, and may not account for local conditions, recent changes, or your personal experience level.</p>
      <fieldset class="ai-ff__exp">
        <legend class="ai-ff__exp-q">How would you describe your outdoor experience?</legend>
        <label class="ai-ff__exp-opt">
          <input type="radio" name="ai-ff-exp" value="beginner" class="ai-ff__exp-radio" autocomplete="off"/>
          <span><strong>Beginner</strong> — I mostly walk on marked trails</span>
        </label>
        <label class="ai-ff__exp-opt">
          <input type="radio" name="ai-ff-exp" value="intermediate" class="ai-ff__exp-radio" autocomplete="off"/>
          <span><strong>Intermediate</strong> — I am comfortable on unmarked terrain</span>
        </label>
        <label class="ai-ff__exp-opt">
          <input type="radio" name="ai-ff-exp" value="advanced" class="ai-ff__exp-radio" autocomplete="off"/>
          <span><strong>Advanced</strong> — I regularly undertake technical routes</span>
        </label>
        <label class="ai-ff__exp-opt">
          <input type="radio" name="ai-ff-exp" value="expert" class="ai-ff__exp-radio" autocomplete="off"/>
          <span><strong>Expert</strong> — I have formal mountaineering or rescue training</span>
        </label>
      </fieldset>
      <p class="ai-ff__sub">By using this feature, you confirm that you:</p>
      <ul class="ai-ff__checks" role="list">
        <li>
          <label class="ai-ff__lbl">
            <input type="checkbox" id="ai-ff-c1" class="ai-ff__chk" autocomplete="off"/>
            <span>Understand this score is an estimate, not a professional safety assessment</span>
          </label>
        </li>
        <li>
          <label class="ai-ff__lbl">
            <input type="checkbox" id="ai-ff-c2" class="ai-ff__chk" autocomplete="off"/>
            <span>Will verify conditions through official sources before proceeding</span>
          </label>
        </li>
        <li>
          <label class="ai-ff__lbl">
            <input type="checkbox" id="ai-ff-c3" class="ai-ff__chk" autocomplete="off"/>
            <span>Accept sole responsibility for your outdoor decisions</span>
          </label>
        </li>
      </ul>
      <button type="button" class="ai-ff__btn" id="ai-ff-continue" disabled>I understand — continue</button>
    </div>`;
  document.body.appendChild(wrap);

  const c1 = wrap.querySelector('#ai-ff-c1');
  const c2 = wrap.querySelector('#ai-ff-c2');
  const c3 = wrap.querySelector('#ai-ff-c3');
  const expRadios = Array.from(wrap.querySelectorAll('.ai-ff__exp-radio'));
  const btn = wrap.querySelector('#ai-ff-continue');
  const stopKey = function (e) {
    e.stopPropagation();
    if (e.key === 'Escape') e.preventDefault();
  };
  document.addEventListener('keydown', stopKey, true);
  function sync() {
    const expSelected = expRadios.some((x) => x.checked);
    const ok = c1 && c1.checked && c2 && c2.checked && c3 && c3.checked;
    if (btn) btn.disabled = !(ok && expSelected);
  }
  [c1, c2, c3].forEach((x) => {
    if (x) x.addEventListener('change', sync);
  });
  expRadios.forEach((x) => x.addEventListener('change', sync));
  const prefill = getStoredExperienceLevel();
  if (prefill) {
    const selected = expRadios.find((x) => x.value === prefill);
    if (selected) selected.checked = true;
  }
  sync();
  wrap.querySelector('.ai-ff__backdrop').addEventListener('click', function (e) {
    e.preventDefault();
    e.stopPropagation();
  });

  btn.addEventListener('click', function () {
    if (btn.disabled) return;
    const selectedExp = expRadios.find((x) => x.checked);
    if (!selectedExp) return;
    const now = new Date().toISOString();
    setStoredExperienceLevel(selectedExp.value);
    appendClientComplianceLog({
      type: 'user_experience_self_reported',
      level: selectedExp.value,
      clientAt: now,
    });
    fetch('/api/compliance/outdoor-experience', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ level: selectedExp.value, client_at: now }),
    })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('experience_ack'))))
      .then((j) => {
        appendClientComplianceLog({
          type: 'user_experience_self_reported_server',
          level: selectedExp.value,
          server_utc: j && j.server_utc,
        });
      })
      .catch(function () {
        appendClientComplianceLog({
          type: 'user_experience_self_reported_server_error',
          level: selectedExp.value,
        });
      });
    setAiFeatureAckRecord(now);
    fetch('/api/compliance/ai-feature-ack', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ accepted: true, client_at: now }),
    })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('ack'))))
      .then((j) => {
        appendClientComplianceLog({ type: 'ai_risk_feature_ack_server', server_utc: j && j.server_utc });
      })
      .catch(function () {
        appendClientComplianceLog({ type: 'ai_risk_feature_ack_server_error' });
      })
      .finally(function () {
        document.removeEventListener('keydown', stopKey, true);
        if (wrap.parentNode) wrap.parentNode.removeChild(wrap);
        if (onComplete) onComplete();
      });
  });
}

function updateOfficialSourcesListButton() {
  const b = document.getElementById('btn-official-sources-list');
  if (b) b.hidden = TRAILS.length === 0;
}

function parseCSV(text) {
  const lines = text.trim().split(/\r?\n/).filter(Boolean);
  if (!lines.length) return [];
  const headers = lines[0].split(',').map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const vals = [];
    let cur = '';
    let q = false;
    for (let i = 0; i < line.length; i++) {
      const c = line[i];
      if (c === '"') q = !q;
      else if (c === ',' && !q) {
        vals.push(cur);
        cur = '';
      } else cur += c;
    }
    vals.push(cur);
    const o = {};
    headers.forEach((h, i) => {
      o[h] = (vals[i] !== undefined ? vals[i] : '').trim();
    });
    return o;
  });
}

function indexById(rows, idKey = 'trail_id') {
  const m = {};
  rows.forEach((r) => {
    const id = Number(r[idKey]);
    if (!Number.isNaN(id)) m[id] = r;
  });
  return m;
}

function buildWaypoints(rows) {
  const by = {};
  rows.forEach((r) => {
    const tid = Number(r.trail_id);
    if (Number.isNaN(tid)) return;
    if (!by[tid]) by[tid] = [];
    by[tid].push(r);
  });
  const out = {};
  Object.keys(by).forEach((tid) => {
    const segs = by[tid].sort((a, b) => Number(a.segment) - Number(b.segment));
    out[tid] = segs.map((s) => [
      parseFloat(s.lat),
      parseFloat(s.lng),
      String(s.segment_status || 'safe').toLowerCase(),
    ]);
  });
  return out;
}

function kmAway(lat1, lon1, lat2, lon2) {
  const R = 6371;
  const toR = (d) => (d * Math.PI) / 180;
  const dLat = toR(lat2 - lat1);
  const dLon = toR(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toR(lat1)) * Math.cos(toR(lat2)) * Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function pathLengthKm(pts) {
  let d = 0;
  for (let i = 1; i < pts.length; i++) {
    d += kmAway(pts[i - 1][0], pts[i - 1][1], pts[i][0], pts[i][1]);
  }
  return d;
}

function sacToDifficulty(tags) {
  const s = (tags?.sac_scale || '').toLowerCase();
  if (s.includes('alpine_hiking') || s.includes('difficult_alpine')) return 'Expert';
  if (s.includes('demanding_mountain')) return 'Hard';
  if (s.includes('mountain_hiking')) return 'Moderate';
  if (s.includes('hiking')) return 'Easy';
  return 'Moderate';
}

function segmentStatuses(geometry) {
  const keys = ['safe', 'safe', 'caution', 'caution', 'risk', 'safe'];
  return geometry.map((_, i) => keys[i % keys.length]);
}

function syntheticFromOsmWay(el) {
  const tags = el.tags || {};
  const geom = el.geometry;
  if (!geom || geom.length < 2) return null;
  const statuses = segmentStatuses(geom);
  const pts = geom.map((n, i) => [n.lat, n.lon, statuses[i] || 'safe']);
  const dist = pathLengthKm(pts);
  if (dist < 0.15) return null;
  const mid = Math.floor(pts.length / 2);
  const lat = pts[mid][0];
  const lng = pts[mid][1];
  const id = 1000000 + el.id;
  const diff = sacToDifficulty(tags);
  const elev = Math.min(2200, Math.max(80, dist * 140));
  const t = {
    id,
    name: tags.name || 'Unnamed path',
    lat,
    lng,
    dist: Math.round(dist * 10) / 10,
    rating: 4.3,
    type: 'OSM',
    surf: tags.surface || 'mixed',
    water: tags.drinking_water === 'yes' ? 2 : 0,
    temp: 16,
    hum: 52,
    wind: 11,
    vis: 14,
    rain: 32,
    sky: 'Partly cloudy',
    pressure: 1015,
    updatedMin: 12,
    goodHiking: true,
    inc: 0,
    incNote: 'No incident dataset for OSM paths',
    canopy: 45,
    exposure: tags.exposure ? String(tags.exposure) : 'medium',
    soil: 'medium',
    envNote: tags.description ? String(tags.description).slice(0, 120) : 'OpenStreetMap contributor data',
    avalanche: tags.avalanche === 'yes' ? 'moderate' : 'none',
    diff,
    elev: Math.round(elev),
    technical: Math.min(10, 3.5 + dist * 0.35 + (diff === 'Expert' ? 2 : 0)),
    narrow: ['narrow', 'yes'].includes(String(tags.width || '').toLowerCase()),
    rockiness: tags.surface === 'rock' || tags.surface === 'stone' ? 'high' : 'medium',
    complexityNote: tags.description
      ? String(tags.description).slice(0, 140)
      : 'Geometry from OpenStreetMap (estimate risk locally).',
    predictionRisk: null,
    predictionConf: null,
    predictionNote: 'Heuristic risk only — wire your model for OSM trails later.',
    source: 'osm',
    osmWayId: el.id,
  };
  const r = riskScoreHeuristic(t);
  t.statusKey = riskToStatusKey(r);
  return { trail: t, points: pts };
}

function mergeTrailRows(trails, weather, incidents, env, complexity, predictions) {
  const w = indexById(weather);
  const inc = indexById(incidents);
  const e = indexById(env);
  const c = indexById(complexity);
  const p = indexById(predictions);

  return trails.map((t) => {
    const id = Number(t.id);
    const wt = w[id] || {};
    const ic = inc[id] || {};
    const ev = e[id] || {};
    const cx = c[id] || {};
    const pr = p[id] || {};

    return {
      id,
      name: t.name,
      lat: parseFloat(t.lat),
      lng: parseFloat(t.lng),
      dist: parseFloat(t.distance_km),
      rating: parseFloat(t.rating),
      type: t.trail_type,
      surf: t.surface,
      water: parseInt(t.water_sources, 10) || 0,
      temp: parseFloat(wt.temp_c) || 15,
      hum: parseFloat(wt.humidity_pct) || 50,
      wind: parseFloat(wt.wind_kmh) || 10,
      vis: parseFloat(wt.visibility_km) || 15,
      rain: parseFloat(wt.precipitation_pct) || 30,
      sky: wt.sky_condition || '—',
      pressure: parseFloat(wt.pressure_hpa) || 1013,
      updatedMin: parseInt(wt.updated_min_ago, 10) || 0,
      goodHiking: (wt.good_hiking || '').toLowerCase() === 'yes',
      inc: parseInt(ic.incidents_last_year, 10) || 0,
      incNote: ic.severity_note || '',
      canopy: parseInt(ev.canopy_pct, 10) || 0,
      exposure: ev.exposure || 'medium',
      soil: ev.soil_stability || 'medium',
      envNote: ev.wildlife_notes || '',
      avalanche: ev.avalanche_risk || 'none',
      diff: cx.difficulty || 'Moderate',
      elev: parseFloat(cx.elevation_gain_m) || 0,
      technical: parseFloat(cx.technical_score_1_10) || 5,
      narrow: (cx.narrow_passages || '').toLowerCase() === 'yes',
      rockiness: cx.rockiness || 'medium',
      complexityNote: cx.notes || '',
      predictionRisk:
        pr.blended_risk_0_10 !== undefined && pr.blended_risk_0_10 !== ''
          ? parseFloat(pr.blended_risk_0_10)
          : null,
      predictionConf: pr.confidence_0_1 !== undefined ? parseFloat(pr.confidence_0_1) : null,
      predictionNote: pr.model_note || '',
      source: 'csv',
    };
  }).map((row) => {
    row.statusKey = riskToStatusKey(displayRisk(row));
    return row;
  });
}

function riskScoreHeuristic(t) {
  const diffMap = { Easy: 2, Moderate: 4.5, Hard: 7.5, Expert: 9.5 };
  const diffS = diffMap[t.diff] || 5;
  const elevS = Math.min(10, t.elev / 150);
  const incS = Math.min(10, t.inc * 1.2);
  const precipS = (t.rain / 100) * 10;
  const humS = (t.hum / 100) * 5;
  const windS = Math.min(10, t.wind / 4);
  const weatherS = precipS * 0.5 + humS * 0.25 + windS * 0.25;
  const visS = Math.max(0, 10 - t.vis * 0.4);
  const raw = diffS * 0.25 + elevS * 0.2 + incS * 0.2 + weatherS * 0.2 + visS * 0.15;
  return Math.min(10, Math.max(1, parseFloat(raw.toFixed(1))));
}

function displayRisk(t) {
  if (t.predictionRisk !== null && !Number.isNaN(t.predictionRisk)) return t.predictionRisk;
  return riskScoreHeuristic(t);
}

function riskMeta(s) {
  if (s <= 3) return { label: 'Lower', color: '#22c55e', cls: 'safe' };
  if (s <= 5.5) return { label: 'Moderate', color: '#f59e0b', cls: 'caution' };
  if (s <= 7.5) return { label: 'Elevated', color: '#f97316', cls: 'risk' };
  return { label: 'Very elevated', color: '#ef4444', cls: 'danger' };
}

const TIER_COLOR = { safe: '#22c55e', caution: '#f59e0b', risk: '#f97316', danger: '#ef4444' };
const SEG_COLOR = { safe: '#22c55e', caution: '#f59e0b', risk: '#f97316', danger: '#ef4444' };

function skyEmoji(sky) {
  const s = (sky || '').toLowerCase();
  if (s.includes('storm')) return '⛈️';
  if (s.includes('fog')) return '🌫️';
  if (s.includes('cloud')) return '⛅';
  if (s.includes('clear') || s.includes('sun')) return '☀️';
  if (s.includes('overcast')) return '☁️';
  return '🌤️';
}

function setAreaLabel(text) {
  const el = document.getElementById('sb-area-label');
  if (el) el.textContent = text;
}

function setSearchCenter(lat, lng, label) {
  searchCenter = { lat, lng, label: label || 'Search' };
  setAreaLabel(`Near: ${searchCenter.label}`);
}

async function nominatimSearch(q) {
  const url = `${NOMINATIM}?format=json&q=${encodeURIComponent(q)}&limit=12&addressdetails=0`;
  const res = await fetch(url, { headers: { ...HTTP_UA, Accept: 'application/json' } });
  if (!res.ok) throw new Error('Geocoding failed');
  const data = await res.json();
  if (!data.length) throw new Error('Place or mountain not found');
  const peakFirst = data.find(
    (x) =>
      x.class === 'natural' &&
      ['peak', 'volcano', 'ridge', 'cliff', 'saddle'].includes(x.type)
  );
  const p = peakFirst || data[0];
  const lat = parseFloat(p.lat);
  const lon = parseFloat(p.lon);
  let south;
  let north;
  let west;
  let east;
  if (p.boundingbox && p.boundingbox.length >= 4) {
    south = parseFloat(p.boundingbox[0]);
    north = parseFloat(p.boundingbox[1]);
    west = parseFloat(p.boundingbox[2]);
    east = parseFloat(p.boundingbox[3]);
  } else {
    const pad = 0.06;
    south = lat - pad;
    north = lat + pad;
    west = lon - pad;
    east = lon + pad;
  }
  const pad = 0.02;
  return {
    lat,
    lon,
    displayName: p.display_name || q,
    south: south - pad,
    west: west - pad,
    north: north + pad,
    east: east + pad,
  };
}

async function overpassNamedPaths(south, west, north, east) {
  const q = `[out:json][timeout:55];
(
  way["highway"="path"]["name"](${south},${west},${north},${east});
  way["highway"="footway"]["name"](${south},${west},${north},${east});
  way["highway"="steps"]["name"](${south},${west},${north},${east});
);
out geom;`;

  const res = await fetch(OVERPASS, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...HTTP_UA },
    body: 'data=' + encodeURIComponent(q),
  });
  if (!res.ok) throw new Error('Overpass request failed');
  return res.json();
}

async function overpassPeaks(south, west, north, east) {
  const q = `[out:json][timeout:45];
(
  node["natural"="peak"]["name"](${south},${west},${north},${east});
);
out body;
(
  way["natural"="peak"]["name"](${south},${west},${north},${east});
);
out center;`;

  const res = await fetch(OVERPASS, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...HTTP_UA },
    body: 'data=' + encodeURIComponent(q),
  });
  if (!res.ok) throw new Error('Overpass peaks request failed');
  return res.json();
}

function parsePeaksFromOverpass(json) {
  const raw = [];
  for (const el of json.elements || []) {
    let lat;
    let lon;
    if (el.type === 'node' && el.lat != null && el.lon != null) {
      lat = el.lat;
      lon = el.lon;
    } else if (el.type === 'way' && el.center) {
      lat = el.center.lat;
      lon = el.center.lon;
    } else continue;
    const name = el.tags?.name;
    if (!name) continue;
    let ele = null;
    if (el.tags?.ele != null) {
      const e = String(el.tags.ele).replace(/,/g, '.');
      const n = parseFloat(e);
      if (!Number.isNaN(n)) ele = Math.round(n);
    }
    raw.push({ name, lat, lon, ele, osmId: el.id, osmType: el.type });
  }
  const byName = new Map();
  for (const p of raw) {
    const k = p.name.toLowerCase();
    if (!byName.has(k)) byName.set(k, p);
  }
  return Array.from(byName.values())
    .map((p, i) => ({ ...p, id: 6000000 + i }))
    .slice(0, 80);
}

function buildOsmTrailsFromOverpass(json) {
  const elements = json.elements || [];
  const byName = new Map();
  for (const el of elements) {
    if (el.type !== 'way' || !el.geometry || el.geometry.length < 3) continue;
    const built = syntheticFromOsmWay(el);
    if (!built) continue;
    const { trail, points } = built;
    const prev = byName.get(trail.name);
    if (!prev || pathLengthKm(points) > pathLengthKm(prev.points)) {
      byName.set(trail.name, { trail, points });
    }
  }
  const list = Array.from(byName.values());
  list.sort((a, b) => pathLengthKm(b.points) - pathLengthKm(a.points));
  return list.slice(0, 55);
}

function applyOsmDataset(items, centerLat, centerLng, label) {
  dataSource = 'osm';
  TRAILS = items.map((x) => x.trail);
  WAYPOINTS = {};
  items.forEach((x) => {
    WAYPOINTS[x.trail.id] = x.points;
  });
  setSearchCenter(centerLat, centerLng, label);
}

async function fetchOsmForBbox(south, west, north, east) {
  const [pathJson, peakJson] = await Promise.all([
    overpassNamedPaths(south, west, north, east),
    overpassPeaks(south, west, north, east),
  ]);
  return {
    items: buildOsmTrailsFromOverpass(pathJson),
    peaks: parsePeaksFromOverpass(peakJson),
  };
}

async function loadCsvDemo() {
  const base = 'data/';
  const [trailsT, weatherT, incT, envT, cxT, predT, wpT] = await Promise.all([
    fetch(base + 'trails.csv').then((r) => r.text()),
    fetch(base + 'weather.csv').then((r) => r.text()),
    fetch(base + 'incidents.csv').then((r) => r.text()),
    fetch(base + 'environment.csv').then((r) => r.text()),
    fetch(base + 'complexity.csv').then((r) => r.text()),
    fetch(base + 'predictions.csv').then((r) => r.text()),
    fetch(base + 'waypoints.csv').then((r) => r.text()),
  ]);
  const trails = parseCSV(trailsT);
  TRAILS = mergeTrailRows(
    trails,
    parseCSV(weatherT),
    parseCSV(incT),
    parseCSV(envT),
    parseCSV(cxT),
    parseCSV(predT)
  );
  WAYPOINTS = buildWaypoints(parseCSV(wpT));
  dataSource = 'csv';
  MOUNTAINS = [];
  setSearchCenter(47.3769, 8.5417, 'Zürich (demo CSV)');
}

async function searchPlaceAndLoadTrails() {
  const input = document.getElementById('place-search');
  const q = (input && input.value.trim()) || '';
  if (!q) return;
  const list = document.getElementById('trail-list');
  if (list) list.innerHTML = '<div class="list-status">Searching & loading OSM trails + peaks…</div>';
  try {
    const geo = await nominatimSearch(q);
    setSearchCenter(geo.lat, geo.lon, geo.displayName.split(',').slice(0, 2).join(','));
    const { items, peaks } = await fetchOsmForBbox(geo.south, geo.west, geo.north, geo.east);
    MOUNTAINS = peaks;
    if (!items.length && !peaks.length) {
      if (list) list.innerHTML = '<div class="list-status">No named paths or peaks in this area — zoom out or try “Load in map view”.</div>';
      map.setView([geo.lat, geo.lon], 12);
      refreshAfterDataLoad();
      return;
    }
    applyOsmDataset(items, geo.lat, geo.lon, searchCenter.label);
    map.setView([geo.lat, geo.lon], 12);
    refreshAfterDataLoad();
  } catch (e) {
    console.error(e);
    if (list) list.innerHTML = `<div class="list-status list-err">${String(e.message || e)}</div>`;
  }
}

async function loadTrailsNearMe() {
  const list = document.getElementById('trail-list');
  if (!navigator.geolocation) {
    if (list) list.innerHTML = '<div class="list-status list-err">Geolocation not available in this browser.</div>';
    return;
  }
  if (list) list.innerHTML = '<div class="list-status">Getting your location…</div>';
  navigator.geolocation.getCurrentPosition(
    async (pos) => {
      const lat = pos.coords.latitude;
      const lng = pos.coords.longitude;
      const pad = 0.05;
      try {
        setSearchCenter(lat, lng, 'Your location');
        const { items, peaks } = await fetchOsmForBbox(lat - pad, lng - pad, lat + pad, lng + pad);
        MOUNTAINS = peaks;
        if (!items.length && !peaks.length) {
          if (list) list.innerHTML = '<div class="list-status">No named paths or peaks here — pan the map and try “Load in map view”.</div>';
          map.setView([lat, lng], 13);
          refreshAfterDataLoad();
          return;
        }
        applyOsmDataset(items, lat, lng, 'Your location');
        map.setView([lat, lng], 13);
        refreshAfterDataLoad();
      } catch (e) {
        console.error(e);
        if (list) list.innerHTML = `<div class="list-status list-err">${String(e.message || e)}</div>`;
      }
    },
    () => {
      if (list) list.innerHTML = '<div class="list-status list-err">Location permission denied.</div>';
    },
    { enableHighAccuracy: true, timeout: 15000 }
  );
}

async function loadTrailsInMapView() {
  if (!map) return;
  const b = map.getBounds();
  const south = b.getSouth();
  const west = b.getWest();
  const north = b.getNorth();
  const east = b.getEast();
  const list = document.getElementById('trail-list');
  if (list) list.innerHTML = '<div class="list-status">Loading trails & peaks in view…</div>';
  try {
    const { items, peaks } = await fetchOsmForBbox(south, west, north, east);
    MOUNTAINS = peaks;
    const c = map.getCenter();
    if (!items.length && !peaks.length) {
      if (list) list.innerHTML = '<div class="list-status">No named paths or peaks in this view — zoom/pan and retry.</div>';
      refreshAfterDataLoad();
      return;
    }
    applyOsmDataset(items, c.lat, c.lng, 'Map view');
    refreshAfterDataLoad();
  } catch (e) {
    console.error(e);
    if (list) list.innerHTML = `<div class="list-status list-err">${String(e.message || e)}</div>`;
  }
}

async function restoreDemoCsv() {
  const list = document.getElementById('trail-list');
  if (list) list.innerHTML = '<div class="list-status">Loading demo data…</div>';
  try {
    await loadCsvDemo();
    map.setView([47.38, 8.55], 11);
    refreshAfterDataLoad();
  } catch (e) {
    console.error(e);
    if (list) list.innerHTML = '<div class="list-status list-err">Could not load CSV demo.</div>';
  }
}

const PEAK_WEATHER_STUB = {
  sky: 'Partly cloudy',
  temp: 12,
  wind: 15,
  hum: 50,
  vis: 20,
  rain: 25,
  pressure: 1015,
  updatedMin: 15,
  goodHiking: true,
};

function renderMountainMarkers() {
  if (!mountainGroup) return;
  mountainGroup.clearLayers();
  MOUNTAINS.forEach((m) => {
    const ico = L.divIcon({
      className: '',
      html: '<div class="peak-mk">▲</div>',
      iconSize: [28, 28],
      iconAnchor: [14, 14],
    });
    L.marker([m.lat, m.lng], { icon: ico })
      .addTo(mountainGroup)
      .on('click', () => selectMountain(m.id));
  });
}

function renderMountainList() {
  const list = document.getElementById('mountain-list');
  const cnt = document.getElementById('mountain-count');
  if (!list) return;
  if (!MOUNTAINS.length) {
    list.innerHTML =
      dataSource === 'csv'
        ? '<div class="list-status">Search a place to load OSM peaks near your search.</div>'
        : '<div class="list-status">No named peaks in this area — try a wider search or different map view.</div>';
    if (cnt) cnt.textContent = '0';
    return;
  }
  const sorted = [...MOUNTAINS].sort((a, b) => {
    const da = kmAway(searchCenter.lat, searchCenter.lng, a.lat, a.lng);
    const db = kmAway(searchCenter.lat, searchCenter.lng, b.lat, b.lng);
    return da - db;
  });
  list.innerHTML = '';
  let shown = 0;
  sorted.forEach((m) => {
    if (!m.name.toLowerCase().includes(mountainFilterQ)) return;
    shown++;
    const away = kmAway(searchCenter.lat, searchCenter.lng, m.lat, m.lng).toFixed(1);
    const div = document.createElement('div');
    div.className = 'mc-row' + (selectedMountainId === m.id ? ' active' : '');
    div.innerHTML = `
      <div class="mc-name">${escapeHtml(m.name)}</div>
      <div class="mc-meta">${away} km from search${m.ele != null ? ` · ${m.ele} m` : ''}</div>`;
    div.addEventListener('click', () => selectMountain(m.id));
    list.appendChild(div);
  });
  if (cnt) cnt.textContent = String(shown);
}

function selectMountain(id) {
  selectedMountainId = id;
  selectedId = null;
  pathGroup.clearLayers();
  const m = MOUNTAINS.find((x) => x.id === id);
  if (!m) return;
  map.setView([m.lat, m.lng], 14);
  renderMountainDetail(m);
  document.getElementById('gear').innerHTML =
    '<div class="empty"><span>🎒</span><p>Suggested gear lists apply to <strong>trail routes</strong> — select a named path in the list above</p></div>';
  renderList();
  renderMountainList();
  renderMarkers();
  renderMountainMarkers();
}

function renderMountainDetail(m) {
  const away = kmAway(searchCenter.lat, searchCenter.lng, m.lat, m.lng).toFixed(1);
  document.getElementById('detail').innerHTML = `
    <div class="detail-official-bar">
      <button type="button" class="btn-official-sources">Official sources</button>
    </div>
    <div class="dp-hd">
      <div>
        <div class="dp-title">${escapeHtml(m.name)} <span class="src-badge">Peak · OSM</span></div>
        <div class="dp-sub">${m.ele != null ? `${m.ele} m (if tagged)` : 'No elevation tag'} · ${away} km from search</div>
      </div>
      <button type="button" class="dp-close" id="dp-close-btn" aria-label="Close">✕</button>
    </div>
    <div class="metric-grid" style="grid-template-columns:1fr">
      <div class="metric-card">
        <span class="mc-lbl">About this peak</span>
        <p class="metric-desc" style="margin-top:8px;font-size:13px">Summit from OpenStreetMap (<code>natural=peak</code>). Use named trails for approach; verify conditions locally.</p>
        <p class="metric-desc" style="margin-top:10px"><strong>Coordinates</strong> ${m.lat.toFixed(5)}, ${m.lng.toFixed(5)}</p>
      </div>
    </div>`;
  updateHeaderWeather(PEAK_WEATHER_STUB);
  renderConditionsPanel(PEAK_WEATHER_STUB);
  document.getElementById('dp-close-btn').addEventListener('click', closeDetail);
}

function filterMountains() {
  const inp = document.getElementById('search-mountain');
  mountainFilterQ = inp ? inp.value.toLowerCase() : '';
  renderMountainList();
}

function refreshAfterDataLoad() {
  selectedId = null;
  selectedMountainId = null;
  pathGroup.clearLayers();
  renderMarkers();
  renderMountainMarkers();
  renderList();
  renderMountainList();

  const sortedT = [...TRAILS].sort(
    (a, b) =>
      kmAway(searchCenter.lat, searchCenter.lng, a.lat, a.lng) -
      kmAway(searchCenter.lat, searchCenter.lng, b.lat, b.lng)
  );
  const sortedM = [...MOUNTAINS].sort(
    (a, b) =>
      kmAway(searchCenter.lat, searchCenter.lng, a.lat, a.lng) -
      kmAway(searchCenter.lat, searchCenter.lng, b.lat, b.lng)
  );

  const distT = sortedT[0]
    ? kmAway(searchCenter.lat, searchCenter.lng, sortedT[0].lat, sortedT[0].lng)
    : Infinity;
  const distM = sortedM[0]
    ? kmAway(searchCenter.lat, searchCenter.lng, sortedM[0].lat, sortedM[0].lng)
    : Infinity;

  if (sortedT.length && sortedM.length) {
    if (distT <= distM) {
      updateHeaderWeather(sortedT[0]);
      renderConditionsPanel(sortedT[0]);
      selectTrail(sortedT[0].id);
    } else {
      selectMountain(sortedM[0].id);
    }
  } else if (sortedT[0]) {
    updateHeaderWeather(sortedT[0]);
    renderConditionsPanel(sortedT[0]);
    selectTrail(sortedT[0].id);
  } else if (sortedM[0]) {
    selectMountain(sortedM[0].id);
  } else {
    document.getElementById('detail').innerHTML =
      '<div class="empty"><span>🗺️</span><p>No trails or peaks to show</p></div>';
    document.getElementById('gear').innerHTML =
      '<div class="empty"><span>🎒</span><p>Gear list appears here</p></div>';
  }
}

function initMap() {
  map = L.map('map', { zoomControl: false }).setView([47.38, 8.55], 11);
  L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
    maxZoom: 17,
    attribution: '© <a href="https://opentopomap.org">OpenTopoMap</a>',
  }).addTo(map);
  L.control.zoom({ position: 'bottomright' }).addTo(map);
  markerGroup = L.layerGroup().addTo(map);
  pathGroup = L.layerGroup().addTo(map);
  mountainGroup = L.layerGroup().addTo(map);

  const leg = L.control({ position: 'bottomleft' });
  leg.onAdd = () => {
    const d = L.DomUtil.create('div', 'map-legend');
    d.innerHTML =
      '<span class="leg s">Lower</span><span class="leg c">Moderate</span><span class="leg r">Elevated</span><span class="leg d">Very elevated</span><span class="leg p">Peak</span><span class="leg ld" title="Fewer than 15 recorded incidents in the surrounding area (aggregated)">Limited data</span>';
    return d;
  };
  leg.addTo(map);
}

function trailMarkerLabel(tierKey) {
  return { safe: 'L', caution: 'M', risk: 'E', danger: 'H' }[String(tierKey).toLowerCase()] || '·';
}

function renderMarkers() {
  markerGroup.clearLayers();
  TRAILS.forEach((t) => {
    const sk = t.statusKey || riskToStatusKey(displayRisk(t));
    const limited = isLimitedDataZone(t);
    const col = limited ? '#78716c' : (TIER_COLOR[sk] || '#94a3b8');
    const mkLabel = limited ? '?' : trailMarkerLabel(sk);
    const ico = L.divIcon({
      className: '',
      html: `<div class="trail-mk${limited ? ' trail-mk--limited' : ''}" style="background:${col}">${mkLabel}</div>`,
      iconSize: [30, 30],
      iconAnchor: [15, 15],
    });
    L.marker([t.lat, t.lng], { icon: ico })
      .addTo(markerGroup)
      .on('click', () => selectTrail(t.id));
  });
}

function renderPath(id) {
  pathGroup.clearLayers();
  const pts = WAYPOINTS[id];
  if (!pts || pts.length < 2) return;
  for (let i = 0; i < pts.length - 1; i++) {
    L.polyline(
      [
        [pts[i][0], pts[i][1]],
        [pts[i + 1][0], pts[i + 1][1]],
      ],
      {
        color: SEG_COLOR[pts[i][2]] || '#94a3b8',
        weight: 5,
        opacity: 0.9,
      }
    ).addTo(pathGroup);
  }
  map.fitBounds(L.latLngBounds(pts.map((p) => [p[0], p[1]])), { padding: [60, 60] });
}

function updateHeaderWeather(t) {
  const el = document.getElementById('header-weather');
  if (!el || !t) return;
  const badge = t.goodHiking
    ? '<span class="hd-badge">Mild conditions (estimate)</span>'
    : '<span class="hd-badge hd-badge-warn">Conditions warrant a closer look</span>';
  el.innerHTML = `
    <span>${skyEmoji(t.sky)} <b>${t.sky}</b></span>
    <span>🌡️ <b>${Math.round(t.temp)}°C</b></span>
    <span>💨 Wind ${Math.round(t.wind)} km/h</span>
    <span>💧 Hum. ${Math.round(t.hum)}%</span>
    <span>👁️ Vis. ${t.vis} km</span>
    <span>🔽 ${Math.round(t.pressure)} hPa</span>
    ${badge}`;
}

function renderConditionsPanel(t) {
  const panel = document.getElementById('conditions-panel');
  if (!panel || !t) return;
  const badge = t.goodHiking
    ? '<span class="cond-badge ok">Mild conditions (estimate)</span>'
    : '<span class="cond-badge warn">Review forecast and local info</span>';
  panel.innerHTML = `
    <div class="cond-hd">
      <span class="cond-title">Current conditions</span>
      <span class="cond-updated">Updated ${t.updatedMin} min ago</span>
    </div>
    <div class="cond-main">
      <div class="cond-temp-block">
        <span class="cond-big">${Math.round(t.temp)}°C</span>
        <div class="cond-sky">${skyEmoji(t.sky)} ${t.sky}</div>
        ${badge}
      </div>
      <div class="cond-metrics">
        <div class="cm"><span>💨</span><b>${Math.round(t.wind)}</b><small>km/h</small></div>
        <div class="cm"><span>💧</span><b>${Math.round(t.hum)}</b><small>%</small></div>
        <div class="cm"><span>👁️</span><b>${t.vis}</b><small>km</small></div>
        <div class="cm"><span>🔽</span><b>${Math.round(t.pressure)}</b><small>hPa</small></div>
      </div>
    </div>
    <p class="wx-attr" role="note">${escapeHtml(WEATHER_ATTRIBUTION_TEXT)}</p>`;
  panel.hidden = false;
}

function renderList() {
  const list = document.getElementById('trail-list');
  const sorted = [...TRAILS].sort((a, b) => {
    const da = kmAway(searchCenter.lat, searchCenter.lng, a.lat, a.lng);
    const db = kmAway(searchCenter.lat, searchCenter.lng, b.lat, b.lng);
    return da - db;
  });
  list.innerHTML = '';
  let shown = 0;

  sorted.forEach((t) => {
    const s = displayRisk(t);
    const rm = riskMeta(s);
    const sk0 = t.statusKey || riskToStatusKey(displayRisk(t));
    const limited = isLimitedDataZone(t);
    const matchFilter =
      activeFilter === 'all' || (!limited && sk0 === activeFilter);
    const matchSearch = t.name.toLowerCase().includes(searchQ);
    if (!matchFilter || !matchSearch) return;
    shown++;

    const away = kmAway(searchCenter.lat, searchCenter.lng, t.lat, t.lng).toFixed(1);
    const tierLine = statusTierUserLine(sk0);
    const gatePending = !limited && needsLowerModerateSourceGate(t) && !hasOfficialSourcesAck();

    const headBadge = gatePending
      ? '<span class="sbadge sbadge-gate">Official sources check required</span>'
      : limited
        ? '<span class="sbadge sbadge-limited">Limited data zone</span>'
        : '<span class="sbadge ' + sk0 + ' sbadge-tier">' + escapeHtml(tierLine) + '</span>';
    const footBlock = gatePending
      ? '<div class="tc-ft"><p class="tc-gate-hint">The score is hidden until you open this route and complete the on-screen check (lower and moderate risk bands).</p></div>'
      : limited
        ? '<div class="tc-ft tc-ft--limited">' + limitedDataZoneMessageHtml() + '</div>'
        : '<div class="tc-ft"><div class="tc-ft-top">' +
          '<div class="tc-bar"><div style="width:' +
          s * 10 +
          '%;background:' +
          rm.color +
          '"></div></div>' +
          '<div class="tc-score-tlabel-wrap">' +
          '<span class="tc-score" style="color:' +
          rm.color +
          '">' +
          s.toFixed(1) +
          '</span>' +
          aiArt50LabelHtml() +
          '</div></div>' +
          '<p class="score-confidence tc-score-footnote">' +
          escapeHtml(riskConfidenceLine(t)) +
          '</p></div>';

    const div = document.createElement('div');
    div.className = 'tc' + (selectedId === t.id && selectedMountainId == null ? ' active' : '');
    div.dataset.id = t.id;
    div.innerHTML =
      '<div class="tc-thumb" aria-hidden="true">🏔️</div>' +
      '<div class="tc-body"><div class="tc-hd"><div><div class="tc-name">' +
      escapeHtml(t.name) +
      '</div><div class="tc-meta">' +
      away +
      ' km from search · ' +
      t.diff +
      ' · ★ ' +
      t.rating +
      ' · ' +
      t.dist +
      ' km</div></div>' +
      headBadge +
      '</div>' +
      footBlock +
      '</div>';
    div.addEventListener('click', () => selectTrail(t.id));
    list.appendChild(div);
  });

  const cnt = document.getElementById('trail-count');
  if (cnt) cnt.textContent = `${shown} trail${shown !== 1 ? 's' : ''}`;

  const listBanner = document.getElementById('ai-safety-list-banner');
  if (listBanner) {
    listBanner.textContent = AI_SAFETY_DISCLAIMER;
    listBanner.hidden = TRAILS.length === 0;
  }
  updateOfficialSourcesListButton();
}

function escapeHtml(s) {
  const d = document.createElement('div');
  d.textContent = s;
  return d.innerHTML;
}

function filterTrails() {
  const inp = document.getElementById('search');
  searchQ = inp ? inp.value.toLowerCase() : '';
  renderList();
}

function setFilter(btn) {
  document.querySelectorAll('.fb').forEach((b) => b.classList.remove('active'));
  btn.classList.add('active');
  activeFilter = btn.dataset.f;
  renderList();
}

function selectTrail(id) {
  selectedMountainId = null;
  const t = TRAILS.find((x) => x.id === id);
  if (!t) return;
  if (needsLowerModerateSourceGate(t) && !hasOfficialSourcesAck() && !isLimitedDataZone(t)) {
    showOfficialSourcesModal(function () {
      selectTrail(id);
    });
    return;
  }
  selectedId = id;
  renderPath(id);
  renderDetail(t);
  renderGear(t);
  renderList();
  renderMountainList();
  updateHeaderWeather(t);
  renderConditionsPanel(t);
}

function closeDetail() {
  selectedId = null;
  selectedMountainId = null;
  pathGroup.clearLayers();
  document.getElementById('detail').innerHTML =
    '<div class="empty"><span>🗺️</span><p>Select a trail or peak for details</p></div>';
  document.getElementById('gear').innerHTML =
    '<div class="empty"><span>🎒</span><p>Gear list appears here</p></div>';
  map.setView([searchCenter.lat, searchCenter.lng], 11);
  const sorted = [...TRAILS].sort(
    (a, b) =>
      kmAway(searchCenter.lat, searchCenter.lng, a.lat, a.lng) -
      kmAway(searchCenter.lat, searchCenter.lng, b.lat, b.lng)
  );
  const first = sorted[0];
  if (first) {
    updateHeaderWeather(first);
    renderConditionsPanel(first);
  }
  renderList();
  renderMountainList();
}

function diffIndex(d) {
  const o = { Easy: 0, Moderate: 1, Hard: 2, Expert: 3 };
  return o[d] !== undefined ? o[d] : 1;
}

function renderDetail(t) {
  const s = displayRisk(t);
  const h = riskScoreHeuristic(t);
  const rm = riskMeta(s);
  const sk = t.statusKey || riskToStatusKey(s);
  const tierLine = statusTierUserLine(sk);
  const tempOk = t.temp >= 10 && t.temp <= 25;
  const elevTag =
    t.elev > 800 ? ['Strenuous', 'xhigh'] : t.elev > 400 ? ['Moderate', 'mod'] : ['Gentle', 'low'];
  const diffTag = {
    Easy: ['Beginner', 'low'],
    Moderate: ['Intermediate', 'mod'],
    Hard: ['Advanced', 'high'],
    Expert: ['Expert', 'xhigh'],
  }[t.diff] || ['—', 'mod'];
  const techBar = Math.min(100, (t.technical / 10) * 100);
  const diffBar = (diffIndex(t.diff) / 3) * 100;
  const src = t.source === 'osm' ? '<span class="src-badge">OpenStreetMap</span>' : '';
  const limited = isLimitedDataZone(t);
  const rscBlock = limited
    ? `<div class="rsc rsc--limited">${limitedDataZoneMessageHtml()}</div>`
    : `<div class="rsc">
      <div class="rsc-l">
        <div class="rsc-title">Risk estimates from environmental data (0–10, informational)</div>
        <div class="donut-wrap">
          <svg class="donut-svg" viewBox="0 0 120 120">
            <circle class="donut-track" cx="60" cy="60" r="44" fill="none" stroke="#e7e5e4" stroke-width="12"/>
            <circle class="donut-fill" cx="60" cy="60" r="44" fill="none" stroke="${rm.color}" stroke-width="12"
              stroke-dasharray="${2 * Math.PI * 44}" stroke-dashoffset="${2 * Math.PI * 44 * (1 - s / 10)}"
              transform="rotate(-90 60 60)" stroke-linecap="round"/>
            <text x="60" y="58" text-anchor="middle" class="donut-num" fill="${rm.color}">${s.toFixed(1)}</text>
            <text x="60" y="76" text-anchor="middle" class="donut-sub">out of 10 (estimate)</text>
          </svg>
        </div>
        ${aiArt50LabelHtml()}
        <p class="score-confidence rsc-confidence-below-donut">${escapeHtml(riskConfidenceLine(t))}</p>
        <p class="pred-foot">
          ${t.predictionNote ? `<span class="pred-note">${escapeHtml(t.predictionNote)}</span>` : ''}
          ${t.predictionConf !== null && !Number.isNaN(t.predictionConf) ? `<span class="pred-conf">Model output ~${Math.round(t.predictionConf * 100)}%</span>` : ''}
        </p>
        <p class="pred-alt">Rule-based (comparison): <span class="pred-alt-row"><strong>${h.toFixed(1)}</strong>${aiArt50LabelHtml('compact')}</span></p>
      </div>
      <div class="rsc-r">
        <div class="rf"><span>Slope</span><div class="rf-bar"><div style="width:${techBar}%;background:#818cf8"></div></div></div>
        <div class="rf"><span>Weather</span><div class="rf-bar"><div style="width:${t.rain}%;background:#38bdf8"></div></div></div>
        <div class="rf"><span>Terrain</span><div class="rf-bar"><div style="width:${diffBar}%;background:#fb923c"></div></div></div>
        <div class="rf"><span>History</span><div class="rf-bar"><div style="width:${Math.min(100, t.inc * 12)}%;background:#f43f5e"></div></div></div>
        <div class="esti-summary" style="background:${rm.color}22;border:1px solid ${rm.color}44">
          <span style="color:${rm.color};font-weight:600">${escapeHtml(tierLine)}</span>
        </div>
      </div>
    </div>`;

  document.getElementById('detail').innerHTML = `
    <p class="ai-safety-disclaimer ai-safety-disclaimer--detail" role="note">${escapeHtml(AI_SAFETY_DISCLAIMER)}</p>
    <div class="detail-official-bar">
      <button type="button" class="btn-official-sources">Official sources</button>
    </div>
    <div class="dp-hd">
      <div>
        <div class="dp-title">${escapeHtml(t.name)} ${src}</div>
        <div class="dp-sub">${t.type} · ${t.surf} · ★ ${t.rating}</div>
      </div>
      <button type="button" class="dp-close" id="dp-close-btn" aria-label="Close">✕</button>
    </div>

    <div class="metric-grid">
      <div class="metric-card">
        <div class="metric-card-hd">
          <span class="mc-lbl">Temperature</span>
          <span class="mc-tag ${tempOk ? 'low' : 'mod'}">${tempOk ? 'Typical range' : 'Worth a check'}</span>
        </div>
        <div class="metric-val">${Math.round(t.temp)}°C</div>
        <div class="metric-bar"><div style="width:${Math.min(100, (t.temp / 35) * 100)}%"></div></div>
        <p class="metric-desc">Reported range only — your comfort may differ.</p>
      </div>
      <div class="metric-card">
        <div class="metric-card-hd">
          <span class="mc-lbl">Elevation gain</span>
          <span class="mc-tag ${elevTag[1]}">${elevTag[0]}</span>
        </div>
        <div class="metric-val">${Math.round(t.elev)} m</div>
        <div class="metric-bar warn"><div style="width:${Math.min(100, t.elev / 15)}%"></div></div>
        <p class="metric-desc">${escapeHtml(t.complexityNote || 'Mind slope and distance.')}</p>
      </div>
      <div class="metric-card">
        <div class="metric-card-hd">
          <span class="mc-lbl">Trail difficulty</span>
          <span class="mc-tag ${diffTag[1]}">${diffTag[0]}</span>
        </div>
        <div class="metric-val">${t.diff}</div>
        <div class="metric-bar danger"><div style="width:${diffBar}%"></div></div>
        <p class="metric-desc">${t.inc} incident${t.inc !== 1 ? 's' : ''} last year · ${t.rockiness} surface</p>
      </div>
    </div>

    <div class="env-strip">
      <span>🌲 Canopy ~${t.canopy}%</span>
      <span>⛰️ Exposure: ${t.exposure}</span>
      <span>🧱 Soil: ${t.soil}</span>
      ${t.avalanche !== 'none' ? `<span>❄️ Avalanche: ${t.avalanche}</span>` : ''}
    </div>

    ${rscBlock}`;

  document.getElementById('dp-close-btn').addEventListener('click', closeDetail);
}

function buildGear(t) {
  const gear = [];
  if (['Hard', 'Expert'].includes(t.diff))
    gear.push({
      id: 'boots',
      ico: '🥾',
      name: 'Waterproof hiking boots',
      pri: 'CRITICAL',
      reason: `Mud/wet possible; ${t.surf} surface. Ankle support matters.`,
    });
  if (t.elev > 400)
    gear.push({
      id: 'poles',
      ico: '🪄',
      name: 'Trekking poles',
      pri: t.elev > 800 ? 'HIGH' : 'MEDIUM',
      reason: `${Math.round(t.elev)} m gain — reduces knee strain.`,
    });
  if (t.water === 0 || t.dist > 6)
    gear.push({
      id: 'water',
      ico: '💧',
      name: 'Extra water (3 L min)',
      pri: 'CRITICAL',
      reason:
        t.water === 0 ? 'No reliable water on route.' : 'Long route — carry enough to drink.',
    });
  if (t.rain > 25)
    gear.push({
      id: 'jacket',
      ico: '🧥',
      name: 'Rain jacket',
      pri: t.rain > 50 ? 'CRITICAL' : 'HIGH',
      reason: `${Math.round(t.rain)}% chance of precipitation.`,
    });
  if (t.temp < 16)
    gear.push({
      id: 'layers',
      ico: '🧣',
      name: 'Insulation / layers',
      pri: 'HIGH',
      reason: `~${Math.round(t.temp)}°C — cools quickly at altitude.`,
    });
  if (t.dist > 8 || ['Hard', 'Expert'].includes(t.diff))
    gear.push({
      id: 'firstaid',
      ico: '🩺',
      name: 'First aid kit',
      pri: 'HIGH',
      reason: 'Long or technical route — carry basic care items.',
    });
  if (['Expert', 'Hard'].includes(t.diff))
    gear.push({
      id: 'nav',
      ico: '🧭',
      name: 'Navigation (GPS / map)',
      pri: 'HIGH',
      reason: 'Complex terrain — do not rely on signs alone.',
    });
  gear.push({
    id: 'sun',
    ico: '🕶️',
    name: 'Sun protection',
    pri: 'MEDIUM',
    reason: 'SPF 30+ and sunglasses recommended.',
  });
  return gear;
}

function renderGear(t) {
  const gear = buildGear(t);
  const stored = JSON.parse(localStorage.getItem('gear_' + t.id) || '{}');
  const ready = gear.filter((g) => stored[g.id]).length;
  const priCls = { CRITICAL: 'crit', HIGH: 'high', MEDIUM: 'med' };
  const giCls = { CRITICAL: 'crit', HIGH: 'high', MEDIUM: '' };

  document.getElementById('gear').innerHTML = `
    <div class="gear-hd">
      <span class="gear-title">Gear suggestions</span>
      <span class="gear-prog-lbl">${ready}/${gear.length} ready</span>
    </div>
    <div class="gear-prog-bar"><div style="width:${gear.length ? (ready / gear.length) * 100 : 0}%"></div></div>
    <div class="gear-list">
      ${gear
        .map(
          (g) => `
        <div class="gi ${giCls[g.pri] || ''}">
          <div class="gi-ico">${g.ico}</div>
          <div class="gi-body">
            <div class="gi-top">
              <span class="gi-name">${escapeHtml(g.name)}</span>
              <span class="gi-badge ${priCls[g.pri] || 'med'}">${g.pri}</span>
            </div>
            <div class="gi-reason">${escapeHtml(g.reason)}</div>
            <label class="gi-chk">
              <input type="checkbox" data-tid="${t.id}" data-gid="${g.id}" ${stored[g.id] ? 'checked' : ''}/>
              <span>I have this</span>
            </label>
          </div>
        </div>`
        )
        .join('')}
    </div>`;

  document.getElementById('gear').querySelectorAll('input[type="checkbox"]').forEach((cb) => {
    cb.addEventListener('change', () => {
      toggleGear(cb.dataset.tid, cb.dataset.gid, cb.checked);
    });
  });
}

function toggleGear(tid, gid, val) {
  const k = 'gear_' + tid;
  const s = JSON.parse(localStorage.getItem(k) || '{}');
  s[gid] = val;
  localStorage.setItem(k, JSON.stringify(s));
  const t = TRAILS.find((x) => String(x.id) === String(tid));
  if (t) renderGear(t);
}

// When this script is injected after /api/auth/me (index-boot.js), DOMContentLoaded has
// already fired — register both paths so the map and CSV load in every case.
function finishMapBoot() {
  renderMarkers();
  renderMountainMarkers();
  renderList();
  renderMountainList();
  const first = TRAILS[0];
  if (first) {
    updateHeaderWeather(first);
    renderConditionsPanel(first);
    setTimeout(() => selectTrail(first.id), 400);
  }

  updateOfficialSourcesListButton();

  const ps = document.getElementById('place-search');
  if (ps) {
    ps.addEventListener('keydown', (ev) => {
      if (ev.key === 'Enter') {
        ev.preventDefault();
        searchPlaceAndLoadTrails();
      }
    });
  }
}

async function bootApp() {
  ensureMandatoryLimitFooter();
  initMap();
  initAiArt50Ui();
  initOfficialSourcesUi();
  initPrivacySettingsUi();
  try {
    await loadCsvDemo();
  } catch (e) {
    console.error(e);
    document.getElementById('detail').innerHTML =
      '<div class="empty"><p>Could not load data. Open via a local server (not file://).</p></div>';
    return;
  }

  if (!(await hasCompletedMandatoryOnboarding())) {
    showMandatoryOnboardingModal(function () {
      if (!hasAiFeatureAck()) {
        showAiFeatureDisclaimerModal(finishMapBoot);
        return;
      }
      finishMapBoot();
    });
    return;
  }

  if (!hasAiFeatureAck()) {
    showAiFeatureDisclaimerModal(finishMapBoot);
    return;
  }
  finishMapBoot();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => {
    void bootApp();
  });
} else {
  void bootApp();
}

window.filterTrails = filterTrails;
window.setFilter = setFilter;
window.closeDetail = closeDetail;
window.searchPlaceAndLoadTrails = searchPlaceAndLoadTrails;
window.loadTrailsNearMe = loadTrailsNearMe;
window.loadTrailsInMapView = loadTrailsInMapView;
window.restoreDemoCsv = restoreDemoCsv;
window.filterMountains = filterMountains;
window.openOfficialChecklistModal = openOfficialChecklistModal;
window.showAiFeatureDisclaimerModal = showAiFeatureDisclaimerModal;
window.openPrivacySettingsModal = openPrivacySettingsModal;
